spring:
  datasource:
    url: jdbc:postgresql://localhost:8088/profile
    username: profile
    password: profile
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port : 8084